version: "3"

services:
  restic-pg-dump:
    environment:
      B2_ACCOUNT_ID:
      B2_ACCOUNT_KEY:
      # BACKUP_SCHEDULE: '0 * * * *'  # Hourly
      # PRUNE_SCHEDULE: '0 14 * * 0'  # Sunday midnight, AEST. Use '' to disable.
      PGHOST:
      PGPASSWORD:
      # PGPORT: 5432
      PGUSER:
      # RESTIC_KEEP_HOURLY: 24
      # RESTIC_KEEP_DAILY: 7
      # RESTIC_KEEP_WEEKLY: 4
      # RESTIC_KEEP_MONTHLY: 12
      RESTIC_PASSWORD:
      RESTIC_REPOSITORY:
    image: dockershepherd/restic-pg-dump-b2
    restart: always
